
---
- name: Expose app and scale it
  hosts: local

  tasks:

    - name: Write service manifest
      copy:
        dest: /tmp/service.yml
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: weather-ml-service
          spec:
            type: NodePort
            selector:
              app: weather-ml
            ports:
              - protocol: TCP
                port: 5000
                targetPort: 5000
                nodePort: 30001

    - name: Apply service
      command: kubectl apply -f /tmp/service.yml

    - name: Scale deployment to 3 replicas
      command: kubectl scale deployment weather-ml-deployment --replicas=3
